let newObj = {
    "accountNumber": "14859",
    "subAccountNumber": "",
    "processingLocation": "PHL",
    "includeRate": true,
    "labelType": "PDF",
    "orderNumber": "6417210",
    "dispatchNumber": "0",
    "packageID": "MESSIANICTEST123",
    "recipientTaxID": null,
    "returnFirstName": "Brian",
    "returnLastName": "Doe.",
    "returnCompanyName": "MVI",
    "returnAddressLine1": "430 Westinghouse",
    "returnAddressLine2": "",
    "returnAddressLine3": "",
    "returnCity": "Charlotte",
    "returnProvince": "NC",
    "returnPostalCode": "28273",
    "returnCountryCode": "US",
    "returnPhone": "555-555-555",
    "returnEmail": "returns@gmail.com",
    "recipientFirstName": "Helena",
    "recipientLastName": "Breckenridge",
    "recipientBusinessName": "",
    "recipientAddressLine1": "184A Pittwater Road",
    "recipientAddressLine2": null,
    "recipientAddressLine3": null,
    "recipientCity": "Gladesville",
    "recipientProvince": "",
    "recipientPostalCode": "211",
    "recipientCountryCode": "AU",
    "recipientPhone": "6316816793",
    "recipientEmail": "user@test.com",
    "totalPackageWeight": 0.37,
    "weightUnit": "Lb",
    "dimLength": 0,
    "dimWidth": 0,
    "dimHeight": 0,
    "dimUnit": "IN",
    "totalPackageValue": 29,
    "currencyType": "USD",
    "productCode": "A112",
    "customerReferenceNumber1": "302-7156956-2315512",
    "customerReferenceNumber2": null,
    "customerReferenceNumber3": null,
    "contentType": "M",
    "packageContentDescription": "Books and Media",
    "items": [
        {
            "sku": "SKU5783SKU_22261690599",
            "itemDescription": "Book",
            "unitPrice": 11.49,
            "quantity": 1,
            "unitWeight": 1.1,
            "countryOfOrigin": "US",
            "htsNumber": "490199"
        }
    ],
    "vatNumber": ""
}