let newObj = {
    "accountNumber": "14859",
    "subAccountNumber": null,
    "processingLocation": "PHL",
    "includeRate": null,
    "failLabelIfNoRate": null,
    "labelType": "ANY",
    "orderNumber": 6417210,
    "dispatchNumber": "11195102",
    "recipientTaxID": null,
    "returnFirstName": "Brian",
    "returnLastName": "Russ",
    "returnCompanyName": "MVI",
    "returnAddressLine1": "4301 Westinghouse Blvd",
    "returnAddressLine2": null,
    "returnAddressLine3": null,
    "returnCity": "Charlotte",
    "returnProvince": "NC",
    "returnPostalCode": "28273",
    "returnCountryCode": "US",
    "returnPhone": "704-943-6500",
    "returnEmail": "info@sidroth.org",
    "recipientFirstName": "Helena",
    "recipientLastName": "Breckenridge",
    "recipientBusinessName": "",
    "recipientAddressLine1": "184A Pittwater Road",
    "recipientAddressLine2": "Unit 38",
    "recipientAddressLine3": "",
    "recipientCity": "Gladesville",
    "recipientPostalCode": "2111",
    "recipientCountryCode": "AU",
    "totalPackageWeight": "0.37000",
    "weightUnit": "Lb",
    "dimLength": null,
    "dimWidth": null,
    "dimHeight": null,
    "dimUnit": null,
    "totalPackageValue": 29,
    "currencyType": "USD",
    "productCode": "A112",
    "customerReferenceNumber1": null,
    "customerReferenceNumber2": null,
    "customerReferenceNumber3": null,
    "contentType": "M",
    "packageContentDescription": "Educ. Materials - Not for Resale",
    "vatNumber": null,
    "sellerName": null,
    "sellerAddressLine1": null,
    "sellerAddressLine2": null,
    "sellerAddressLine3": null,
    "sellerCity": null,
    "sellerProvince": null,
    "sellerPostalCode": null,
    "sellerCountryCode": null,
    "sellerPhone": null,
    "sellerEmail": null,
    "items": [
        {
            "sku": "3974",
            "itemDescription": "(3974) N. Alvarez -  Prophetic P",
            "unitPrice": "10.00",
            "quantity": 1,
            "unitWeight": "0.00",
            "countryOfOrigin": "US",
            "htsNumber": "8523.49.3000"
        },
        {
            "sku": "3973",
            "itemDescription": "(3973) N. Alvarez - 3 CD Set: As",
            "unitPrice": "19.00",
            "quantity": 1,
            "unitWeight": "0.00",
            "countryOfOrigin": "US",
            "htsNumber": "8523.49.3000"
        }
    ],
    "shippingCost": 0,
    "packageID": "11195102"
}